FROM php:8.1-cli

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

RUN docker-php-ext-install mysqli pdo pdo_mysql

WORKDIR /var/www

COPY ./www /var/www/html
COPY ./tests /var/www/tests

CMD ["php", "/var/www/tests/run_tests.php"]
